apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: electrical-crayfish-java-quarkus-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/electrical-crayfish-java-quarkus